name: Push
on:
  push:
    branches:
      - master

jobs:
  docker:
    name: Build Docker container and push to ghcr.io
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v30
        with:
          nix_conf: |
            keep-env-derivations = false
            keep-outputs = false
            max-jobs = auto
            cores = 0
            substituters = https://cache.nixos.org https://nix-community.cachix.org
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypQtVrp8wSJr09Kl1Cj6obRh7f0= nix-community.cachix.org-1:mB9FSh9qF2qLqn8tQ7Dvxlfqwng0m7kbs35atqwvrnE=

      - name: GHA Nix cache
        uses: nix-community/cache-nix-action@v6
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
          gc-max-store-size-linux: 2G
          purge: true
          purge-prefixes: nix-${{ runner.os }}-
          purge-created: 0
          purge-last-accessed: 0
          purge-primary-key: never

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        env:
          PUBLIC_TURNSTILE_SITE_KEY: ${{ secrets.PUBLIC_TURNSTILE_SITE_KEY }}
          TURNSTILE_SECRET_TOKEN: ${{ secrets.TURNSTILE_SECRET_TOKEN }}
          OWM_API_KEY: ${{ secrets.OWM_API_KEY }}
          LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
          ASTRO_DB_REMOTE_URL: ${{ secrets.ASTRO_DB_REMOTE_URL }}
          ASTRO_DB_APP_TOKEN: ${{ secrets.ASTRO_DB_APP_TOKEN }}
          ASTRO_DB_GUESTBOOK_DASHBOARD_URL: ${{ secrets.ASTRO_DB_GUESTBOOK_DASHBOARD_URL }}
          DISCORD_CONTACT_WEBHOOK_URL: ${{ secrets.DISCORD_CONTACT_WEBHOOK_URL }}
          DISCORD_GUESTBOOK_WEBHOOK_URL: ${{ secrets.DISCORD_GUESTBOOK_WEBHOOK_URL }}
          DISCORD_USER_ID: ${{ secrets.DISCORD_USER_ID }}
          LANYARD_API_URL: ${{ secrets.LANYARD_API_URL }}
          COMMIT_HASH: ${{ github.sha }}
          COMMIT_DATE: ${{ github.event.head_commit.timestamp }}
        run: |
          nix build .#container --max-jobs auto --impure --fallback
          docker load < result
          docker tag sapphic-moe ghcr.io/sapphosys/sapphic-moe:latest
          docker push ghcr.io/sapphosys/sapphic-moe:latest
