name: Push
on:
  push:
    branches:
      - master

jobs:
  docker:
    name: Build Docker container and push to ghcr.io
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v30
        with:
          nix_conf: |
            keep-env-derivations = false
            keep-outputs = false
            max-jobs = auto
            cores = 0
            substituters = https://cache.nixos.org https://sapphic-moe.cachix.org
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= sapphic-moe.cachix.org-1:tKNbRYC7VnC7xhdputyclq8bqPRTid3UmMjGP7du+C8=

      - name: Setup Cachix
        uses: cachix/cachix-action@v15
        with:
          name: sapphic-moe
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          useDaemon: false

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          nix build .#container --max-jobs auto
          docker load < result
          docker tag sapphic-moe ghcr.io/sapphosys/sapphic-moe:latest
          docker push ghcr.io/sapphosys/sapphic-moe:latest
